tree_menu/tree/urls.py
from django.urls import path

from tree.views import TreeView

app_name = "tree"

urlpatterns = [
    path("tree/<slug:slug>/", TreeView.as_view(), name="tree"),
]

tree_menu/tree_menu/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("tree.urls")),
]

tree_menu/tree/models.py
from django.db import models


class Menu(models.Model):
    """Меню."""

    name = models.CharField(
        "Название",
        max_length=255,
        unique=True,
    )
    slug = models.SlugField(
        "Идентификатор меню",
        max_length=255,
    )

    class Meta:
        verbose_name = "Меню"
        verbose_name_plural = "Меню"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/tree/{self.slug}/"


class Item(models.Model):
    """Пункты меню."""

    name = models.CharField(
        "Название",
        max_length=100,
        unique=True,
        blank=False,
    )
    slug = models.SlugField(
        "Идентификатор пункта",
        max_length=255,
    )
    parent = models.ForeignKey(
        "self",
        null=True,
        blank=True,
        related_name="childrens",
        on_delete=models.CASCADE,
    )
    menu = models.ForeignKey(
        Menu,
        blank=True,
        related_name="items",
        on_delete=models.CASCADE,
    )

    class Meta:
        verbose_name = "Пункт меню"
        verbose_name_plural = "Пункты меню"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/tree/{self.slug}/"

tree_menu/tree/views.py
from django.views.generic import TemplateView


class TreeView(TemplateView):
    """
    Функция для отображения отображения меню.
    """

    template_name = "tree/index.html"

    def get_context_data(self, **kwargs):
        """Формирует контекст, предаёт данные из запроса пользователя."""
        context = super().get_context_data(**kwargs)
        slug_menu = self.kwargs["slug"]
        context["slug_menu"] = slug_menu
        return context

tree_menu/tree/templates/base.html
<!DOCTYPE html> 
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Menu{% endblock %}</title>    
  </head>
  <body>       
    <main>
      {% block content %}
        Контент не подвезли 
      {% endblock %}
    </main>
  </body>
</html> 

tree_menu/tree/templates/tree/index.html
{% extends 'base.html' %}
{% load show_menu %}
{% block title %} Menu {% endblock %}
{% block content %}
  <div class="container py-5">     
    <h3>
      <a href="{% url 'tree:tree' "main_menu" %}">
        Main_menu
      </a>
      <br> 
    </h3>
    {% draw_menu 'main_menu' %}
  </div>
{% endblock %}

tree_menu/tree/templates/tree/menu.html
{% load show_menu %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Меню</title>
  </head>
  <body>
    {% draw_menu name %}
  </body>
</html>